/*
 * Copyright TESAIoT Platform contributors
 * SPDX-License-Identifier: Apache-2.0
 *
 * Origin: TESAIoT Secure IoT Platform (relicensed subset for the Community Edition).
 */

import React, { useState, useEffect } from 'react';
import { Card, CardContent, CardHeader, CardTitle } from '@/components/ui/card';
import { Button } from '@/components/ui/button';
import { Label } from '@/components/ui/label';
import { 
  Select, 
  SelectContent, 
  SelectItem, 
  SelectTrigger, 
  SelectValue,
  SelectGroup,
  SelectLabel
} from '@/components/ui/select';
import { Badge } from '@/components/ui/badge';
import { Alert, AlertDescription } from '@/components/ui/alert';
import { Separator } from '@/components/ui/separator';
import { 
  BarChart3, 
  Gauge, 
  TrendingUp, 
  Activity,
  Info,
  Zap,
  Database,
  Eye,
  Settings
} from 'lucide-react';
import { 
  extractDeviceSchemaFields, 
  generateFieldOptions, 
  getFieldsForWidgetType,
  parseFieldValue,
  type DeviceSchemaFields,
  type SchemaField
} from '../utils/schemaFieldExtractor';

interface WidgetConfig {
  id: string;
  type: string;
  deviceId?: string;
  fieldKey?: string;
  title?: string;
  size: {
    cols: number;
    rows: number;
  };
  options?: Record<string, any>;
}

interface SchemaBasedWidgetConfigProps {
  devices: any[];
  widgetType: string;
  onConfigured: (config: WidgetConfig) => void;
  onCancel: () => void;
  initialConfig?: Partial<WidgetConfig>;
}

const WIDGET_TYPES = {
  'gauge': {
    icon: <Gauge className="h-4 w-4" />,
    name: 'Gauge',
    description: 'Circular gauge for numeric values',
    defaultSize: { cols: 2, rows: 2 },
    supportedTypes: ['number', 'integer'],
    categories: ['sensor', 'computed']
  },
  'line-chart': {
    icon: <TrendingUp className="h-4 w-4" />,
    name: 'Line Chart',
    description: 'Time-series line chart',
    defaultSize: { cols: 4, rows: 3 },
    supportedTypes: ['number', 'integer'],
    categories: ['sensor', 'computed']
  },
  'bar-chart': {
    icon: <BarChart3 className="h-4 w-4" />,
    name: 'Bar Chart',
    description: 'Categorical bar chart',
    defaultSize: { cols: 3, rows: 3 },
    supportedTypes: ['number', 'integer', 'string'],
    categories: ['sensor', 'status', 'computed']
  },
  'stat-card': {
    icon: <Activity className="h-4 w-4" />,
    name: 'Stat Card',
    description: 'Single value display card',
    defaultSize: { cols: 2, rows: 1 },
    supportedTypes: ['number', 'integer', 'string', 'boolean'],
    categories: ['sensor', 'status', 'computed', 'metadata']
  },
  'status-indicator': {
    icon: <Zap className="h-4 w-4" />,
    name: 'Status Indicator',
    description: 'Status light or badge',
    defaultSize: { cols: 1, rows: 1 },
    supportedTypes: ['boolean', 'string'],
    categories: ['status']
  }
};

export const SchemaBasedWidgetConfig: React.FC<SchemaBasedWidgetConfigProps> = ({
  devices,
  widgetType,
  onConfigured,
  onCancel,
  initialConfig
}) => {
  const [deviceFields, setDeviceFields] = useState<DeviceSchemaFields[]>([]);
  const [selectedDeviceField, setSelectedDeviceField] = useState<string>(
    initialConfig?.deviceId && initialConfig?.fieldKey 
      ? `${initialConfig.deviceId}:${initialConfig.fieldKey}` 
      : ''
  );
  const [widgetTitle, setWidgetTitle] = useState(initialConfig?.title || '');
  const [autoGeneratedTitle, setAutoGeneratedTitle] = useState('');
  const [titleManuallySet, setTitleManuallySet] = useState(false);
  const [fieldInfo, setFieldInfo] = useState<SchemaField | null>(null);
  const [hasCompatibleFields, setHasCompatibleFields] = useState(false);

  const widgetTypeInfo = WIDGET_TYPES[widgetType as keyof typeof WIDGET_TYPES] || WIDGET_TYPES['stat-card'];

  useEffect(() => {
    const fields = extractDeviceSchemaFields(devices);
    setDeviceFields(fields);

    // Check if any devices have compatible fields
    const compatibleFields = getFieldsForWidgetType(fields, widgetType);
    setHasCompatibleFields(compatibleFields.length > 0);

    // Auto-select first compatible field if none selected
    if (!selectedDeviceField && compatibleFields.length > 0) {
      const firstField = compatibleFields[0];
      const fieldValue = `${firstField.deviceId}:${firstField.field.key}`;
      setSelectedDeviceField(fieldValue);
    }
  }, [devices, widgetType]);

  useEffect(() => {
    if (selectedDeviceField) {
      const parsed = parseFieldValue(selectedDeviceField);
      if (parsed) {
        const device = deviceFields.find(d => d.deviceId === parsed.deviceId);
        if (device) {
          const field = [...device.telemetryFields, ...device.actuatorFields]
            .find(f => f.key === parsed.fieldKey);
          setFieldInfo(field || null);
          
          // Auto-generate title
          const generatedTitle = field ? `${device.deviceName} - ${field.title}` : '';
          setAutoGeneratedTitle(generatedTitle);
          
          // Update widget title if not manually set
          if (!titleManuallySet && generatedTitle) {
            setWidgetTitle(generatedTitle);
          }
        }
      }
    }
  }, [selectedDeviceField, deviceFields, titleManuallySet]);

  const handleConfigure = () => {
    if (!selectedDeviceField) return;

    const parsed = parseFieldValue(selectedDeviceField);
    if (!parsed) return;

    const config: WidgetConfig = {
      id: `widget-${Date.now()}`,
      type: widgetType,
      deviceId: parsed.deviceId,
      fieldKey: parsed.fieldKey,
      title: widgetTitle || `${widgetTypeInfo.name} Widget`,
      size: widgetTypeInfo.defaultSize,
      options: {
        field: fieldInfo,
        ...initialConfig?.options
      }
    };

    onConfigured(config);
  };

  const fieldOptions = generateFieldOptions(deviceFields, widgetType);
  const groupedOptions = fieldOptions.reduce((groups, option) => {
    if (!groups[option.group]) {
      groups[option.group] = [];
    }
    groups[option.group].push(option);
    return groups;
  }, {} as Record<string, typeof fieldOptions>);

  return (
    <Card className="w-full max-w-2xl mx-auto">
      <CardHeader>
        <CardTitle className="flex items-center gap-2">
          {widgetTypeInfo.icon}
          Configure {widgetTypeInfo.name} Widget
        </CardTitle>
      </CardHeader>
      <CardContent className="space-y-6">
        {/* Widget Type Info */}
        <div className="p-4 bg-muted/50 rounded-lg">
          <div className="flex items-start gap-3">
            <div className="p-2 bg-primary/10 rounded-md">
              {widgetTypeInfo.icon}
            </div>
            <div className="flex-1">
              <h4 className="font-medium">{widgetTypeInfo.name}</h4>
              <p className="text-sm text-muted-foreground mb-2">
                {widgetTypeInfo.description}
              </p>
              <div className="flex gap-2">
                <Badge variant="outline" className="text-xs">
                  {widgetTypeInfo.defaultSize.cols}×{widgetTypeInfo.defaultSize.rows}
                </Badge>
                {widgetTypeInfo.supportedTypes.map(type => (
                  <Badge key={type} variant="secondary" className="text-xs">
                    {type}
                  </Badge>
                ))}
              </div>
            </div>
          </div>
        </div>

        {!hasCompatibleFields ? (
          <Alert>
            <Info className="h-4 w-4" />
            <AlertDescription>
              No devices have schema fields compatible with {widgetTypeInfo.name} widgets. 
              Add device schemas in Device Management → Data Schema to enable field selection.
            </AlertDescription>
          </Alert>
        ) : (
          <>
            {/* Field Selection */}
            <div className="space-y-2">
              <Label htmlFor="device-field">Data Field *</Label>
              <Select 
                value={selectedDeviceField} 
                onValueChange={setSelectedDeviceField}
              >
                <SelectTrigger>
                  <SelectValue placeholder="Select a device field to display..." />
                </SelectTrigger>
                <SelectContent className="max-h-64">
                  {Object.entries(groupedOptions).map(([group, options]) => (
                    <SelectGroup key={group}>
                      <SelectLabel className="flex items-center gap-2">
                        <Database className="h-3 w-3" />
                        {group}
                      </SelectLabel>
                      {options.map(option => {
                        const [deviceName, fieldName] = option.label.split(' - ');
                        return (
                          <SelectItem key={option.value} value={option.value}>
                            <div className="flex items-center gap-2">
                              <Badge 
                                variant={option.field.category === 'sensor' ? 'default' : 'secondary'} 
                                className="text-xs"
                              >
                                {option.field.category}
                              </Badge>
                              <span className="font-bold text-foreground">{deviceName}</span>
                              <span className="text-muted-foreground">-</span>
                              <span className="font-medium text-primary">{fieldName}</span>
                            </div>
                          </SelectItem>
                        );
                      })}
                    </SelectGroup>
                  ))}
                </SelectContent>
              </Select>
              <div className="text-xs text-muted-foreground">
                Fields are automatically filtered for {widgetTypeInfo.name} compatibility
              </div>
            </div>

            {/* Field Information */}
            {fieldInfo && (
              <div className="p-4 border rounded-lg space-y-3">
                <div className="flex items-center gap-2">
                  <Eye className="h-4 w-4" />
                  <span className="font-medium">Field Information</span>
                </div>
                <div className="grid grid-cols-2 gap-4 text-sm">
                  <div>
                    <span className="text-muted-foreground">Type:</span>
                    <span className="ml-2 font-mono">{fieldInfo.type}</span>
                  </div>
                  <div>
                    <span className="text-muted-foreground">Category:</span>
                    <Badge variant="outline" className="ml-2 text-xs">
                      {fieldInfo.category}
                    </Badge>
                  </div>
                  {fieldInfo.unit && (
                    <div>
                      <span className="text-muted-foreground">Unit:</span>
                      <span className="ml-2 font-mono">{fieldInfo.unit}</span>
                    </div>
                  )}
                  {fieldInfo.isRequired && (
                    <div>
                      <span className="text-muted-foreground">Required:</span>
                      <Badge variant="destructive" className="ml-2 text-xs">
                        Yes
                      </Badge>
                    </div>
                  )}
                  {(fieldInfo.minimum !== undefined || fieldInfo.maximum !== undefined) && (
                    <div className="col-span-2">
                      <span className="text-muted-foreground">Range:</span>
                      <span className="ml-2 font-mono">
                        {fieldInfo.minimum ?? '∞'} — {fieldInfo.maximum ?? '∞'}
                      </span>
                    </div>
                  )}
                  {fieldInfo.description && (
                    <div className="col-span-2">
                      <span className="text-muted-foreground">Description:</span>
                      <p className="ml-2 text-sm">{fieldInfo.description}</p>
                    </div>
                  )}
                </div>
              </div>
            )}

            {/* Widget Title */}
            <div className="space-y-2">
              <Label htmlFor="widget-title">Widget Title</Label>
              <input
                id="widget-title"
                type="text"
                value={widgetTitle}
                onChange={(e) => {
                  setWidgetTitle(e.target.value);
                  setTitleManuallySet(e.target.value !== autoGeneratedTitle && e.target.value !== '');
                }}
                placeholder={autoGeneratedTitle || "Enter custom widget title..."}
                className="w-full px-3 py-2 border rounded-md focus:outline-none focus:ring-2 focus:ring-primary"
              />
              <div className="text-xs text-muted-foreground">
                Leave empty for auto-generated title
              </div>
            </div>

            <Separator />

            {/* Action Buttons */}
            <div className="flex justify-end gap-2">
              <Button variant="outline" onClick={onCancel}>
                Cancel
              </Button>
              <Button 
                onClick={handleConfigure}
                disabled={!selectedDeviceField}
              >
                <Settings className="h-4 w-4 mr-2" />
                Create Widget
              </Button>
            </div>
          </>
        )}

        {/* Schema Statistics */}
        <div className="pt-4 border-t">
          <div className="text-xs text-muted-foreground space-y-1">
            <div>Total devices: {devices.length}</div>
            <div>Devices with schemas: {deviceFields.filter(d => d.hasSchema).length}</div>
            <div>Available fields: {fieldOptions.length}</div>
          </div>
        </div>
      </CardContent>
    </Card>
  );
};