# SPDX-License-Identifier: Apache-2.0
# Copyright 2026 TESAIoT Platform contributors.
#
# Originally derived from the TESAIoT Secure IoT Platform; relicensed under the
# Apache License, Version 2.0 by the copyright owner. See the NOTICE file in the
# distribution root for details.

"""
Certificate Download Routes - Best Practices Implementation
Implements CSR certificate downloads following RFC standards and NIST guidelines
"""

from flask import Blueprint, Response, jsonify, g
import logging
import zipfile
import io
import json
from datetime import datetime
import os
from bson import ObjectId
from ..core.auth import require_auth
from ..core.rbac import RBAC
from ..core.database import get_vault_client
from ..services.certificate_service import _build_mqtt_client_config_header_full, download_certificate_file as svc_download_certificate_file
from ..services.vault_certificate_storage_service import vault_certificate_storage_service
from ..services.vault_private_key_storage_service import vault_private_key_storage_service

logger = logging.getLogger(__name__)

# Create Blueprint with the expected URL prefix
cert_download_bp = Blueprint('certificate_downloads', __name__, url_prefix='/api/v1/certificates/devices')

@cert_download_bp.route('/<device_id>/certificate/download/<download_type>', methods=['GET'])
@require_auth
def download_certificate_component(device_id, download_type):
    """
    Download certificate components for a device following best practices:
    - CSR devices: Provide CA chain, device cert, server certs (NO private keys)
    - PKI devices: Same as above, optionally include private key if generated by platform
    
    Based on:
    - RFC 5280: X.509 PKI Certificate Profile
    - RFC 7030: Enrollment over Secure Transport (EST)
    - NIST SP 800-52: TLS Implementation Guidelines
    """
    try:
        # Use proper authenticated MongoDB connection
        from ..core.database import get_db
        db = get_db()
        if db is None:
            logger.error("Failed to get MongoDB connection")
            return jsonify({'error': 'Database connection failed'}), 500
        
        # Validate download type
        valid_types = ['bundle', 'zip', 'ca-chain', 'device-cert', 'mqtt-broker-cert', 'endpoints', 'device-key', 'https-mtls-bundle', 'trustm-starter-bundle']
        if download_type not in valid_types:
            return jsonify({
                'error': 'Invalid download type',
                'valid_types': valid_types
            }), 400
        
        # Find device
        device = db.devices.find_one({'device_id': device_id})
        if not device:
            try:
                device = db.devices.find_one({'_id': ObjectId(device_id)})
            except:
                pass
        
        if not device:
            return jsonify({'error': 'Device not found'}), 404

        # SECURITY (authz/IDOR): enforce per-object organization ownership BEFORE any
        # Vault retrieval or certificate/private-key material is returned. Fail-closed.
        if not RBAC.can_access_organization(g.current_user, device.get('organization_id', '')):
            logger.warning(
                "[SECURITY_VIOLATION_PREVENTED] User %s denied certificate download for device %s (org %s)",
                g.current_user.get('email'), device_id, device.get('organization_id')
            )
            return jsonify({'error': 'Access denied'}), 403

        # Determine if device is Trust M (allows starter bundle without platform certificate)
        auth_mode = str(device.get('auth_mode', 'mtls')).lower()
        metadata = device.get('metadata') or {}
        secure_element = metadata.get('secure_element') or metadata.get('secureElement')
        trust_profile = device.get('trust_profile') or metadata.get('trust_profile')
        factory_uid = metadata.get('factory_uid')
        trustm_uid = device.get('trustm_uid')  # Trust M UID from device record
        trustm_device = auth_mode in ('optiga_trust_mtls', 'trustm_mtls', 'optiga_trustm') or \
            secure_element == 'infineon_optiga_trust_m' or \
            trust_profile == 'infineon_optiga_trust_m' or \
            (factory_uid and metadata.get('protected_update_enabled')) or \
            bool(trustm_uid)  # Device with Trust M UID is a Trust M device

        # Check if device has certificate (not required for CA chain download or Trust M starter bundle)
        cert_serial = device.get('certificate_serial')
        if download_type not in ('ca-chain', 'trustm-starter-bundle'):
            if not cert_serial and not device.get('certificate'):
                return jsonify({'error': 'Device has no certificate. Please generate or submit CSR first.'}), 404
        if download_type == 'trustm-starter-bundle' and not trustm_device:
            return jsonify({'error': 'Device is not configured for OPTIGA Trust M'}), 400
        
        def _render_trustm_starter_bundle():
            """Prepare Trust M starter bundle response via certificate service."""
            try:
                result = svc_download_certificate_file(
                    device_id,
                    'trustm-starter-bundle',
                    g.current_user,
                    skip_audit=True
                )
                if isinstance(result, tuple) and len(result) == 2 and isinstance(result[0], (bytes, str)):
                    content, filename = result
                    if isinstance(content, str):
                        content = content.encode('utf-8')
                    response = Response(content, mimetype='application/zip')
                    response.headers['Content-Disposition'] = f'attachment; filename={filename}'
                    response.headers['X-Bundle-Type'] = 'trustm-starter'
                    return response
                if isinstance(result, tuple) and len(result) == 2 and isinstance(result[1], int) and result[1] >= 400:
                    return jsonify(result[0]), result[1]
                if hasattr(result, 'status_code'):
                    return result
                raise RuntimeError('Unexpected service return shape for trustm-starter-bundle')
            except Exception as exc:
                logger.error(
                    "Trust M starter bundle preparation failed for %s: %s",
                    device_id,
                    exc,
                    exc_info=True
                )
                return jsonify({'error': 'TRUSTM_STARTER_BUNDLE_FAILED', 'details': str(exc)}), 500

        # Trust M starter bundle: delegate to certificate service immediately (no further processing needed)
        if download_type == 'trustm-starter-bundle':
            return _render_trustm_starter_bundle()

        # Determine if this is a CSR-based device
        is_csr_device = (
            device.get('generation_method') in ['upload_csr', 'upload-csr', 'user_csr'] or
            device.get('csr_provided') is True or
            device.get('csr') is not None
        )

        # Fast-path delegate to service handler for HTTPS mTLS bundle
        if download_type == 'https-mtls-bundle':
            try:
                result = svc_download_certificate_file(device_id, 'https-mtls-bundle', g.current_user, skip_audit=True)
                if isinstance(result, tuple) and len(result) == 2 and isinstance(result[0], (bytes, str)):
                    content, filename = result
                    # bytes or str; ensure bytes
                    if isinstance(content, str):
                        content = content.encode('utf-8')
                    resp = Response(content, mimetype='application/zip')
                    resp.headers['Content-Disposition'] = f'attachment; filename={filename}'
                    return resp
                elif isinstance(result, tuple) and len(result) == 2 and isinstance(result[1], int) and result[1] >= 400:
                    return jsonify(result[0]), result[1]
                elif hasattr(result, 'status_code'):
                    return result
                else:
                    # Unexpected shape: fall through to fallback builder
                    raise RuntimeError('Unexpected service return shape for https-mtls-bundle')
            except Exception as e:
                # Enhanced logging with traceback for root-cause analysis
                logger.error(f"HTTPS mTLS bundle generation failed for {device_id}: {e}", exc_info=True)
                # Fallback: build a minimal, safe ZIP directly (device cert + optional CA + endpoints + README)
                try:
                    # Helper: best-effort PEM extraction
                    def _to_text(x):
                        return x.decode('utf-8') if isinstance(x, (bytes, bytearray)) else x
                    def _extract_pem(val):
                        if val is None:
                            return ''
                        if isinstance(val, (str, bytes, bytearray)):
                            txt = _to_text(val)
                            return txt if '-----BEGIN CERTIFICATE-----' in (txt or '') else ''
                        if isinstance(val, dict):
                            for k in ('certificate_pem', 'certificate', 'pem', 'content'):
                                v = val.get(k)
                                if isinstance(v, (str, bytes, bytearray)):
                                    txt = _to_text(v)
                                    if '-----BEGIN CERTIFICATE-----' in (txt or ''):
                                        return txt
                            return ''
                        if isinstance(val, list):
                            items = []
                            for it in val:
                                pem = _extract_pem(it)
                                if pem:
                                    items.append(pem.strip())
                            return "\n".join(items)
                        txt = _to_text(str(val))
                        return txt if '-----BEGIN CERTIFICATE-----' in (txt or '') else ''

                    # Collect cert and chain from device record with gentle fallbacks
                    cert_pem = _extract_pem(device.get('certificate')) or _extract_pem((device.get('certificate_info') or {}).get('certificate'))
                    chain_raw = device.get('certificate_chain') or (device.get('certificate_info') or {}).get('ca_chain')
                    ca_chain = _extract_pem(chain_raw)

                    if not cert_pem:
                        return jsonify({'error': 'Certificate not available for bundle'}), 404

                    # Env-driven endpoints (safe defaults) — avoid local 'os' binding issues
                    from os import getenv as _getenv
                    api_base = _getenv('TESA_PUBLIC_API_BASE_URL', 'https://localhost')
                    ingest_base = _getenv('TESA_PUBLIC_INGEST_BASE_URL', f"{api_base}:9444")
                    endpoints = json.dumps({
                        'ingest_base_url': ingest_base,
                        'api_base_url': api_base,
                        'tls': {'require_mtls': True, 'alpn': ['h2', 'http/1.1']}
                    }, indent=2)

                    # Build ZIP
                    buf = io.BytesIO()
                    with zipfile.ZipFile(buf, 'w', zipfile.ZIP_DEFLATED) as z:
                        z.writestr(f"{device_id}-certificate.pem", cert_pem)
                        if ca_chain:
                            z.writestr(f"{device_id}-ca-chain.pem", ca_chain)
                        z.writestr('endpoints.json', endpoints)
                        z.writestr('README.txt', (
                            f"TESA IoT — HTTPS + mTLS Bundle\n"
                            f"Device: {device_id}\n"
                            f"Generated: {datetime.now().isoformat()}\n\n"
                            "Includes: device certificate, optional CA chain, endpoints.json.\n"
                            "Private key is not included for CSR-based devices.\n"
                        ))
                    buf.seek(0)
                    resp = Response(buf.getvalue(), mimetype='application/zip')
                    resp.headers['Content-Disposition'] = f'attachment; filename={device_id}-https-mtls-bundle.zip'
                    return resp
                except Exception as fe:
                    logger.error(f"Fallback HTTPS mTLS bundle also failed for {device_id}: {fe}", exc_info=True)
                    return jsonify({'error': 'BUNDLE_GENERATION_FAILED', 'details': str(e)}), 500
        
        # Per RFC 7030 and NIST guidelines: NEVER provide private keys for CSR devices
        if is_csr_device and download_type == 'device-key':
            return jsonify({
                'error': 'Private keys are not available for CSR-based devices',
                'reason': 'Per NIST SP 800-57: Private keys must remain under sole control of the entity',
                'reference': 'RFC 7030 Section 4.1.3'
            }), 403
        
        # Initialize certificate components
        cert_data = None
        ca_chain = None
        mqtt_broker_cert = None
        private_key = None
        organization_id = device.get('organization_id')

        # SECURITY IMPROVEMENT: Try KV v2 storage first (vault_certificate_storage_service)
        # Rule: certificates live in Vault; MongoDB stores only metadata/references.
        try:
            kv2_result = vault_certificate_storage_service.retrieve_certificate(
                device_id=device_id,
                organization_id=organization_id,
                requester={'user_id': g.current_user.get('user_id', 'unknown'), 'role': g.current_user.get('role', 'unknown')}
            )
            if kv2_result and kv2_result.get('certificate_pem'):
                cert_data = kv2_result.get('certificate_pem')
                ca_chain_pem = kv2_result.get('ca_chain_pem')
                if ca_chain_pem:
                    if isinstance(ca_chain_pem, list):
                        ca_chain = '\n'.join(ca_chain_pem)
                    else:
                        ca_chain = ca_chain_pem
                logger.info(f"Retrieved certificate from Vault KV v2 for device: {device_id}")
        except Exception as e:
            logger.debug(f"Vault KV v2 certificate retrieval failed for {device_id}: {e}")

        # BACKWARD COMPATIBILITY: Fallback to PKI engine if not found in KV v2
        if not cert_data and cert_serial:
            vault_client = get_vault_client()
            if vault_client:
                # Try multiple serial formats for Vault compatibility
                serial_formats = [
                    cert_serial,
                    cert_serial.replace(':', '-'),
                    cert_serial.replace('-', ':'),
                    cert_serial.lower().replace(':', '-'),
                    cert_serial.upper().replace(':', '-')
                ]

                # Search for device certificate in Vault PKI engine
                for serial_fmt in serial_formats:
                    vault_paths = [
                        f'pki/cert/{serial_fmt}',
                        f'pki_int/cert/{serial_fmt}',
                        f'pki-int/cert/{serial_fmt}',
                        f'pki-root/cert/{serial_fmt}',
                        f'pki_device/cert/{serial_fmt}'
                    ]

                    for vault_path in vault_paths:
                        try:
                            response = vault_client.read(vault_path)
                            if response and 'data' in response:
                                cert_data = response['data'].get('certificate', '')
                                ca_chain_list = response['data'].get('ca_chain', [])
                                if isinstance(ca_chain_list, list) and ca_chain_list:
                                    ca_chain = '\n'.join(ca_chain_list)
                                if not ca_chain:
                                    ca_chain = response['data'].get('issuing_ca', '')
                                logger.info(f"Retrieved certificate from Vault PKI: {vault_path}")
                                break
                        except Exception as e:
                            logger.debug(f'Vault PKI read failed for {vault_path}: {e}')
                    if cert_data:
                        break

                # Get CA chain if not already retrieved
                if not ca_chain:
                    try:
                        root_ca = ''
                        int_ca = ''
                        # Try multiple mounts for root CA
                        for path in ('pki/cert/ca', 'pki-root/cert/ca'):
                            try:
                                ca_response = vault_client.read(path)
                                if ca_response and 'data' in ca_response:
                                    root_ca = ca_response['data'].get('certificate', '') or root_ca
                            except Exception:
                                continue
                        # Try multiple mounts for intermediate CA
                        for path in ('pki_int/cert/ca', 'pki-int/cert/ca'):
                            try:
                                int_response = vault_client.read(path)
                                if int_response and 'data' in int_response:
                                    int_ca = int_response['data'].get('certificate', '') or int_ca
                            except Exception:
                                continue
                        # Combine CAs into chain (intermediate first if present)
                        ca_chain = f"{int_ca}\n{root_ca}".strip() if (int_ca or root_ca) else None
                    except Exception as e:
                        logger.warning(f"Could not retrieve CA chain from Vault: {e}")

        # Fallback 1: device record (legacy field)
        if not cert_data:
            try:
                cert_data = device.get('certificate')
            except Exception:
                cert_data = None
        # Fallback 2: persisted device_certificates collection (latest by issued_at)
        if not cert_data:
            try:
                latest = db.device_certificates.find_one(
                    {'device_id': device_id}, sort=[('issued_at', -1)]
                )
                if latest:
                    cert_data = latest.get('certificate_pem') or cert_data
                    # Use CA from record if Vault chain not found
                    if not ca_chain:
                        chain_val = latest.get('ca_chain')
                        if isinstance(chain_val, list):
                            ca_chain = "\n".join(chain_val)
                        elif isinstance(chain_val, str):
                            ca_chain = chain_val
                    # Private key for non-CSR devices (server-generated)
                    if not is_csr_device and not private_key:
                        private_key = latest.get('private_key_pem')
            except Exception as e:
                logger.debug(f"device_certificates lookup failed for {device_id}: {e}")
        
        # SECURITY IMPROVEMENT: Try private key from Vault KV v2 first
        try:
            if not is_csr_device and not private_key:
                kv2_key_result = vault_private_key_storage_service.retrieve_private_key(
                    device_id=device_id,
                    organization_id=organization_id,
                    requester={'user_id': g.current_user.get('user_id', 'unknown'), 'role': g.current_user.get('role', 'unknown')}
                )
                if kv2_key_result and kv2_key_result.get('private_key_pem'):
                    private_key = kv2_key_result.get('private_key_pem')
                    logger.info(f"Retrieved private key from Vault KV v2 for device: {device_id}")
        except Exception as e:
            logger.debug(f"Vault KV v2 private key retrieval failed for {device_id}: {e}")

        # BACKWARD COMPATIBILITY: Try private key from device record (legacy)
        try:
            if not is_csr_device and not private_key:
                private_key = device.get('private_key')
        except Exception:
            private_key = None

        # Get MQTT broker certificate (for client to validate server)
        try:
            # This would typically come from your MQTT broker configuration
            mqtt_broker_cert = """-----BEGIN CERTIFICATE-----
MIIFKzCCBBOgAwIBAgISA+Z7u5TKq1MhohVHkKmHoVi1MA0GCSqGSIb3DQEBCwUA
[MQTT Broker Server Certificate]
Contact administrator for actual broker certificate
-----END CERTIFICATE-----"""
            
            # In production, retrieve from EMQX or configuration
            # Example: response = requests.get('http://tesa-emqx:18083/api/v5/mqtt/ssl_certs')
        except:
            pass
        
        # Provide default CA chain if still not found
        if not ca_chain:
            ca_chain = """-----BEGIN CERTIFICATE-----
MIIE4jCCA8qgAwIBAgIUYxYRdh6lMBGaKhynNK7xClU1lQowDQYJKoZIhvcNAQEL
[TESA IoT Platform Root CA]
Please contact administrator for actual CA certificate
-----END CERTIFICATE-----"""
        
        # Provide placeholder certificate if not found but serial exists
        if not cert_data and cert_serial:
            cert_data = f"""-----BEGIN CERTIFICATE-----
Certificate Serial: {cert_serial}
Status: Certificate issued but not yet synchronized
Action: Please contact administrator or wait for synchronization
-----END CERTIFICATE-----"""
        
        # Service endpoints configuration (env-driven with safe defaults)
        MQTT_HOST = os.getenv('TESA_PUBLIC_MQTT_HOST', 'localhost')
        # Mapping: 8884 = Server‑TLS (username/password), 8883 = mTLS (client certificate)
        MQTT_TLS_PORT = int(os.getenv('TESA_PUBLIC_MQTT_TLS_PORT', '8884'))
        MQTT_MTLS_PORT = int(os.getenv('TESA_PUBLIC_MQTT_MTLS_PORT', '8883'))
        MQTT_WS_PORT = int(os.getenv('TESA_PUBLIC_MQTT_WS_PORT', '8083'))
        API_BASE_URL = os.getenv('TESA_PUBLIC_API_BASE_URL', 'https://localhost')
        INGEST_BASE_URL = os.getenv('TESA_PUBLIC_INGEST_BASE_URL', f"{API_BASE_URL}:9444")

        endpoints_config = {
            "mqtt": {
                "tls": {"host": MQTT_HOST, "port": MQTT_TLS_PORT, "protocol": "mqtts"},
                "mtls": {"host": MQTT_HOST, "port": MQTT_MTLS_PORT, "protocol": "mqtts", "client_cert_required": True},
                "websocket": {"host": MQTT_HOST, "port": MQTT_WS_PORT, "path": "/mqtt"}
            },
            "api": {
                "rest": {"host": API_BASE_URL.replace('https://','').replace('http://',''), "port": 443, "protocol": "https", "base_path": "/api/v1"},
                "telemetry": {"endpoint": f"{API_BASE_URL}/api/v1/telemetry", "method": "POST", "auth": "mTLS or API Key"}
            },
            "validation": {
                # Domain-agnostic self-host: derive OCSP/CRL hosts from the
                # install's DOMAIN so a custom domain (e.g. iot.acme.com) does
                # not leak a baked-in tesaiot.dev into downloaded cert-info.
                "ocsp": os.getenv('TESA_PUBLIC_OCSP_URL', f"http://ocsp.{os.getenv('DOMAIN', 'localhost')}"),
                "crl": os.getenv('TESA_PUBLIC_CRL_URL', f"http://crl.{os.getenv('DOMAIN', 'localhost')}/tesa-ca.crl")
            },
            # Flat keys for embedded client auto-detection
            "ingest_base_url": INGEST_BASE_URL,
            "api_base_url": API_BASE_URL,
            "tls": {"require_mtls": True, "alpn": ["h2", "http/1.1"]}
        }
        
        # Robust PEM extraction (avoid writing JSON into .pem files)
        def _to_text(x):
            return x.decode('utf-8') if isinstance(x, (bytes, bytearray)) else x

        def _extract_pem(val):
            """Return a PEM string if present, else empty string.
            Supports dicts like {certificate|certificate_pem|pem|content} and raw str/bytes.
            """
            if val is None:
                return ''
            if isinstance(val, (str, bytes, bytearray)):
                txt = _to_text(val)
                return txt if '-----BEGIN CERTIFICATE-----' in (txt or '') else ''
            if isinstance(val, dict):
                for k in ('certificate_pem', 'certificate', 'pem', 'content'):
                    v = val.get(k)
                    if isinstance(v, (str, bytes, bytearray)):
                        txt = _to_text(v)
                        if '-----BEGIN CERTIFICATE-----' in (txt or ''):
                            return txt
                return ''
            if isinstance(val, list):
                # Join only items that look like PEMs
                peMs = []
                for item in val:
                    pem = _extract_pem(item)
                    if pem:
                        peMs.append(pem.strip())
                return "\n".join(peMs)
            # Fallback to string, but only if it looks like PEM
            txt = _to_text(str(val))
            return txt if '-----BEGIN CERTIFICATE-----' in (txt or '') else ''

        cert_data = _extract_pem(cert_data)
        ca_chain = _extract_pem(ca_chain)
        mqtt_broker_cert = _extract_pem(mqtt_broker_cert) or mqtt_broker_cert or ''

        # If device cert is required but not available as PEM, fail clearly
        if download_type in ['bundle', 'zip', 'device-cert'] and not cert_data:
            return jsonify({'error': 'Certificate not available in PEM format (yet). Please try again shortly.'}), 404

        # Generate response based on download type
        # Support both 'bundle' (canonical) and 'zip' (UI legacy) as complete bundle
        if download_type in ['bundle', 'zip']:
            # Create comprehensive ZIP bundle following best practices
            zip_buffer = io.BytesIO()
            with zipfile.ZipFile(zip_buffer, 'w', zipfile.ZIP_DEFLATED) as zip_file:
                # 1. CA Certificate Chain (MANDATORY per RFC 5280)
                zip_file.writestr('ca-chain.pem', ca_chain)
                
                # 2. Device Certificate (MANDATORY)
                zip_file.writestr(f'{device_id}.pem', cert_data)
                
                # 3. MQTT Broker Certificate (RECOMMENDED per NIST SP 800-52)
                if mqtt_broker_cert:
                    zip_file.writestr('mqtt-broker.pem', mqtt_broker_cert)
                
                # 4. Service Endpoints (RECOMMENDED)
                zip_file.writestr('endpoints.json', json.dumps(endpoints_config, indent=2))
                
                # 5. Private Key (ONLY for non-CSR devices, per NIST SP 800-57)
                if not is_csr_device and private_key:
                    zip_file.writestr(f'{device_id}.key', private_key)
                
                # 6. mqtt_client_config.h helper for embedded clients
                try:
                    # Determine algorithm label
                    algo_label = None
                    if isinstance(device.get('certificate_info'), dict):
                        algo_label = device['certificate_info'].get('key_algorithm') or device['certificate_info'].get('algorithm')
                    if not algo_label:
                        alg_map = {
                            'ecc-p256': 'ECC P-256',
                            'ecc-p384': 'ECC P-384',
                            'rsa-3072': 'RSA 3072',
                            'rsa-4096': 'RSA 4096'
                        }
                        algo_label = alg_map.get(device.get('certificate_algorithm'), 'ECC P-256')

                    header_text = _build_mqtt_client_config_header_full(
                        device_id=device_id,
                        username=device.get('device_id', device_id),
                        auth_mode=device.get('auth_mode', 'mtls'),
                        ca_pem=ca_chain,
                        cert_pem=cert_data,
                        key_pem=(private_key if (private_key and not is_csr_device) else None),
                        algorithm_label=algo_label
                    )
                    zip_file.writestr('mqtt_client_config.h', header_text)
                except Exception as e:
                    logger.warning(f"Failed to generate mqtt_client_config.h for {device_id}: {e}")

                # 7. Auto-generated telemetry code (data_telemetry.c/.h)
                try:
                    from ..services.telemetry_code_generator import add_telemetry_files_to_zip
                    add_telemetry_files_to_zip(zip_file, device, folder_prefix='telemetry')
                except Exception as e:
                    logger.warning(f"Failed to generate telemetry code for {device_id}: {e}")

                # 8. Implementation Guide
                implementation_guide = f"""TESA IoT Platform - Certificate Bundle
=====================================
Generated: {datetime.now().isoformat()}
Device: {device.get('name', device_id)}
Type: {'CSR-Based (User-Managed Keys)' if is_csr_device else 'Platform-Managed PKI'}
Organization: {g.current_user.get('organization_name', 'N/A')}

BUNDLE CONTENTS
===============
1. ca-chain.pem          - Root and intermediate CA certificates (RFC 5280)
2. {device_id}.pem       - Device certificate (X.509v3)
3. mqtt-broker.pem       - MQTT broker server certificate
4. endpoints.json        - Service endpoint configuration
5. mqtt_client_config.h  - PSoC/embedded MQTT client config
6. telemetry/            - Auto-generated C code for telemetry serialization
   - data_telemetry.h    - Header with struct and function prototypes
   - data_telemetry.c    - Source with JSON serialization code
   - README.md           - Usage documentation
7. README.txt            - This implementation guide
{f'8. {device_id}.key     - Private key (KEEP SECURE!)' if not is_csr_device and private_key else ''}

{'⚠️  IMPORTANT: Private key not included (you manage it)' if is_csr_device else ''}

mTLS CONNECTION SETUP
====================

1. MQTT with mTLS (Port 8884):
   mosquitto_pub -h {MQTT_HOST} -p 8884 \\
     --cafile ca-chain.pem \\
     --cert {device_id}.pem \\
     {'--key [YOUR_PRIVATE_KEY]' if is_csr_device else f'--key {device_id}.key'} \\
     -t "devices/{device_id}/telemetry" \\
     -m '{{"temperature": 25.5}}'

2. HTTPS with mTLS:
   curl {API_BASE_URL}/api/v1/devices/telemetry \\
     --cacert ca-chain.pem \\
     --cert {device_id}.pem \\
     {'--key [YOUR_PRIVATE_KEY]' if is_csr_device else f'--key {device_id}.key'} \\
     -H "Content-Type: application/json" \\
     -d '{{"device_id": "{device_id}", "data": {{}}}}'

3. Python Implementation:
   import paho.mqtt.client as mqtt
   import ssl
   
   client = mqtt.Client(client_id="{device_id}")
   client.tls_set(
       ca_certs="ca-chain.pem",
       certfile="{device_id}.pem",
       keyfile={'[YOUR_PRIVATE_KEY]' if is_csr_device else f'"{device_id}.key"'},
       cert_reqs=ssl.CERT_REQUIRED,
       tls_version=ssl.PROTOCOL_TLSv1_2  # Minimum per NIST SP 800-52
   )
   client.connect("{MQTT_HOST}", 8884)

SECURITY REQUIREMENTS
====================
✓ TLS 1.2 minimum (TLS 1.3 recommended) - NIST SP 800-52 Rev 2
✓ Certificate validation required both ways - RFC 5246
✓ Full certificate chain validation - RFC 5280
✓ Check certificate expiration regularly
✓ Implement OCSP/CRL checking if possible - RFC 6960

{'PRIVATE KEY SECURITY (CSR Devices)' if is_csr_device else 'PRIVATE KEY SECURITY'}
{'=' * 35}
{'Your private key is NOT included in this bundle.' if is_csr_device else 'Private key IS included - PROTECT IT!'}
{'You generated and manage the private key locally.' if is_csr_device else 'Store securely and limit access.'}
{'Per NIST SP 800-57: Never share or transmit private keys.' if is_csr_device else 'Per NIST SP 800-57: Protect from unauthorized access.'}
{'Use hardware security (TPM/HSM) when possible.' if True else ''}

CERTIFICATE DETAILS
==================
Serial Number: {cert_serial or 'Pending'}
Valid From: [Check certificate for dates]
Valid Until: [Check certificate for dates]
Issuer: TESA IoT Platform CA
Subject: CN={device_id}

TROUBLESHOOTING
==============
1. Connection refused: Check firewall rules for ports 8883/8884
2. Certificate verification failed: Ensure ca-chain.pem is complete
3. Client certificate rejected: Verify certificate is not expired
4. Permission denied: Check device is authorized in platform

REFERENCES
=========
- RFC 5280: Internet X.509 PKI Certificate and CRL Profile
- RFC 7030: Enrollment over Secure Transport (EST)
- NIST SP 800-52 Rev 2: Guidelines for TLS Implementations
- NIST SP 800-57: Recommendation for Key Management
- OWASP IoT Security Verification Standard

SUPPORT
=======
Technical Documentation: https://tesaiot.github.io/developer-hub
Platform Support: contact your platform administrator

Certificate Serial: {cert_serial or 'N/A'}
Bundle Generated: {datetime.now().isoformat()}
Platform Version: v2025.08
"""
                zip_file.writestr('README.txt', implementation_guide)
            
            zip_buffer.seek(0)
            # Use descriptive filename for MQTTs mTLS bundle
            ts = datetime.now().isoformat().replace(':', '-').split('.')[0]
            bundle_name = f"{device_id}-mqtts-mtls-bundle-{ts}.zip"
            return Response(
                zip_buffer.getvalue(),
                mimetype='application/zip',
                headers={
                    'Content-Disposition': f'attachment; filename={bundle_name}',
                    'X-Certificate-Type': 'CSR-Based' if is_csr_device else 'Platform-PKI',
                    'X-Certificate-Serial': cert_serial or 'pending'
                }
            )
        
        elif download_type == 'ca-chain':
            return Response(
                ca_chain,
                mimetype='application/x-pem-file',
                headers={
                    'Content-Disposition': 'attachment; filename=ca-chain.pem',
                    'X-Certificate-Type': 'CA-Chain'
                }
            )
        
        elif download_type == 'device-cert':
            return Response(
                cert_data,
                mimetype='application/x-pem-file',
                headers={
                    'Content-Disposition': f'attachment; filename={device_id}.pem',
                    'X-Certificate-Serial': cert_serial or 'pending'
                }
            )
        
        elif download_type == 'mqtt-broker-cert':
            return Response(
                mqtt_broker_cert or 'Broker certificate not available',
                mimetype='application/x-pem-file',
                headers={
                    'Content-Disposition': 'attachment; filename=mqtt-broker.pem'
                }
            )
        
        elif download_type == 'endpoints':
            return jsonify(endpoints_config), 200

        # Note: 'https-mtls-bundle' handled by service fast-path above to avoid duplication

        elif download_type == 'device-key' and not is_csr_device:
            if not private_key:
                return jsonify({
                    'error': 'Private key not available',
                    'reason': 'Key may not be stored or device uses external key management'
                }), 404
            return Response(
                private_key,
                mimetype='application/x-pem-file',
                headers={
                    'Content-Disposition': f'attachment; filename={device_id}.key',
                    'X-Warning': 'Private key - handle with extreme care'
                }
            )
        
        elif download_type == 'trustm-starter-bundle':
            # Safety net: if flow reaches here, fall back to service helper
            return _render_trustm_starter_bundle()
        else:
            return jsonify({'error': f'Download type {download_type} not implemented'}), 501
            
    except Exception as e:
        logger.error(f"Certificate download error for device {device_id}: {e}", exc_info=True)
        return jsonify({
            'error': 'Certificate download failed',
            'details': str(e)
        }), 500

@cert_download_bp.route('/<device_id>/certificate/info', methods=['GET'])
@require_auth  
def get_certificate_info(device_id):
    """
    Get certificate information and download options for a device
    """
    try:
        # Use proper authenticated MongoDB connection
        from ..core.database import get_db
        db = get_db()
        if db is None:
            logger.error("Failed to get MongoDB connection")
            return jsonify({'error': 'Database connection failed'}), 500
        
        device = db.devices.find_one({'device_id': device_id})
        if not device:
            return jsonify({'error': 'Device not found'}), 404

        # SECURITY (authz/IDOR): enforce per-object organization ownership. Fail-closed.
        if not RBAC.can_access_organization(g.current_user, device.get('organization_id', '')):
            logger.warning(
                "[SECURITY_VIOLATION_PREVENTED] User %s denied certificate info for device %s (org %s)",
                g.current_user.get('email'), device_id, device.get('organization_id')
            )
            return jsonify({'error': 'Access denied'}), 403

        is_csr_device = (
            device.get('generation_method') in ['upload_csr', 'upload-csr', 'user_csr'] or
            device.get('csr_provided') is True
        )
        # Detect stored private key for platform-generated certs
        has_private_key = False
        if not is_csr_device:
            try:
                has_private_key = bool(device.get('private_key'))
                if not has_private_key:
                    latest = db.device_certificates.find_one(
                        {'device_id': device_id},
                        sort=[('issued_at', -1)]
                    )
                    if latest and latest.get('private_key_pem'):
                        has_private_key = True
            except Exception:
                has_private_key = False
        
        download_options = {
            'bundle': {
                'description': 'Complete certificate bundle with all required files',
                'includes': [
                    'CA certificate chain',
                    'Device certificate', 
                    'MQTT broker certificate',
                    'Service endpoints',
                    'Implementation guide'
                ],
                'excludes': ['Private key'] if is_csr_device else [],
                'recommended': True
            },
            'ca-chain': {
                'description': 'Root and intermediate CA certificates',
                'format': 'PEM',
                'usage': 'Server certificate validation'
            },
            'device-cert': {
                'description': 'Device X.509 certificate',
                'format': 'PEM',
                'usage': 'Client authentication'
            },
            'mqtt-broker-cert': {
                'description': 'MQTT broker server certificate',
                'format': 'PEM',
                'usage': 'Broker identity validation'
            },
            'endpoints': {
                'description': 'Service endpoint configuration',
                'format': 'JSON',
                'usage': 'Connection configuration'
            }
        }

        metadata = device.get('metadata') or {}
        auth_mode = str(device.get('auth_mode', 'mtls')).lower()
        secure_element = metadata.get('secure_element') or metadata.get('secureElement')
        trust_profile = device.get('trust_profile') or metadata.get('trust_profile')
        factory_uid = metadata.get('factory_uid')
        trustm_uid = device.get('trustm_uid')  # Trust M UID from device record
        trustm_device = auth_mode in ('optiga_trust_mtls', 'trustm_mtls', 'optiga_trustm') or \
            secure_element == 'infineon_optiga_trust_m' or \
            trust_profile == 'infineon_optiga_trust_m' or \
            (factory_uid and metadata.get('protected_update_enabled')) or \
            bool(trustm_uid)  # Device with Trust M UID is a Trust M device

        if trustm_device:
            download_options['trustm-starter-bundle'] = {
                'description': 'OPTIGA Trust M starter bundle',
                'format': 'ZIP',
                'usage': 'Factory onboarding (trust anchor, metadata, MQTT header)',
                'notes': 'Use before TESAIoT certificate rotation via Protected Update'
            }
        
        # Policy-aware gating for private key download option
        pol = {}
        try:
            pol = (db.org_policies.find_one({'organization_id': device.get('organization_id')}) or {}).get('certificate', {})
        except Exception:
            pol = {}
        allow_svr_keygen = pol.get('allow_server_side_key_gen', os.environ.get('ALLOW_SERVER_SIDE_KEY_GEN','false').lower() in ('1','true','yes'))
        retain_key_at_rest = pol.get('retain_private_key_at_rest', os.environ.get('RETAIN_PRIVATE_KEY_AT_REST','false').lower() in ('1','true','yes'))
        if not is_csr_device and has_private_key and allow_svr_keygen and retain_key_at_rest:
            download_options['device-key'] = {
                'description': 'Private key (platform-generated only)',
                'format': 'PEM',
                'usage': 'Client authentication',
                'warning': 'Keep secure and never share'
            }
        
        return jsonify({
            'device_id': device_id,
            'device_name': device.get('name'),
            'certificate_type': 'CSR-Based' if is_csr_device else 'Platform-PKI',
            'certificate_serial': device.get('certificate_serial'),
            'has_certificate': bool(device.get('certificate_serial') or device.get('certificate')),
            'has_private_key': has_private_key and allow_svr_keygen and retain_key_at_rest,
            'download_options': download_options,
            'security_notes': {
                'private_key': 'Managed by device owner - not included' if is_csr_device else 'Platform-managed - handle with care',
                'best_practice': 'Download bundle for complete setup files',
                'references': [
                    'RFC 5280 - X.509 PKI Certificate Profile',
                    'NIST SP 800-52 - TLS Guidelines',
                    'NIST SP 800-57 - Key Management'
                ]
            }
        }), 200
        
    except Exception as e:
        logger.error(f"Error getting certificate info: {e}")
        return jsonify({'error': str(e)}), 500
